Divya/fabric sharing
astra-sim/astra-sim pull request #131
Opened 2023-10-31 08:20 UTC by dkadiyala3

## <u>Changes</u>:
1. Added the network io statistics collection module under extern/statistics
2. Fixed the runtime calculation in AnalyticalRemoteMemory::get_remote_mem_runtime(uint64_t tensor_size) to compute in ns.
3. Linked execution-graph-converter-Intel submodule
4. Added `inputs/workload/execution-graph-converter-Intel/conv-spreadsheet-to-exegraph.sh` script to generate the inputs from spreadsheet models into the execution graphs under `inputs/workload/ASTRA-sim-2.0/` folder
5. Added `inputs/workload/conv-text-to-exegraph.sh` script to generate the inputs from ASTRA-sim-1.0 text files into the execution graphs under `inputs/workload/ASTRA-sim-2.0/` folder

2023-10-31 11:41 UTC, TaekyungHeo commented on .gitmodules
> +	url = git@github.com:astra-sim/execution-graph-converter-Intel.git
As the name suggests, we are not allowed to release this repository. We don't have any plan to make it public. Which tool do you need for this PR?

2023-10-31 11:42 UTC, TaekyungHeo commented on astra-sim/network_frontend/analytical/congestion_aware/AstraCongestionApi.cc
> +  //std::cout << "[Before:] event_time: " << event_time << std::endl;
Please remove commented out lines. Commenting lines is not a good practice.

2023-10-31 11:42 UTC, TaekyungHeo commented on astra-sim/network_frontend/analytical/congestion_unaware/AnalyticalNetwork.cc
> +#include "cassert"
I believe you can replace it with #include <cassert>

2023-10-31 11:43 UTC, TaekyungHeo commented on astra-sim/network_frontend/analytical/congestion_unaware/AnalyticalNetwork.cc
> +                                       // 'count' here is the payload size in bytes.
Thanks for adding a comment.

2023-10-31 11:43 UTC, TaekyungHeo commented on astra-sim/network_frontend/analytical/congestion_unaware/AnalyticalNetwork.cc
> +
Please remove this blank line.

2023-10-31 11:43 UTC, TaekyungHeo commented on astra-sim/network_frontend/analytical/congestion_unaware/AnalyticalNetwork.cc
> +  // after the packet is arrived at the dest.
Comments look good.

2023-10-31 11:43 UTC, TaekyungHeo commented on astra-sim/network_frontend/analytical/congestion_unaware/AnalyticalNetwork.cc
> +
Don't need to add a blank line

2023-10-31 11:44 UTC, TaekyungHeo commented on build/astra_analytical/CMakeLists.txt
> +#set(CMAKE_CXX_FLAGS "-Wall -ggdb3 -O3 -Wextra -pedantic -fsanitize=address")
Please avoid adding commented out lines. Instead, you may introduce switches to Cmake.

2023-10-31 11:45 UTC, TaekyungHeo commented on build/astra_analytical/build.sh
> +  #cmake --build . -j "${NUM_THREADS:?}"
Please remove commented out lines

2023-10-31 11:45 UTC, TaekyungHeo commented on extern/statistics/GStats.cc
> +#include "GStats.hh"
Please add a blank line below this line.

2023-10-31 11:49 UTC, TaekyungHeo commented on .gitignore
> +inputs/workload/ASTRA-sim-2.0/*.eg
Please add `inputs/workload/ASTRA-sim-2.0/*.et` as well

2023-10-31 11:50 UTC, TaekyungHeo commented on extern/statistics/GStats.cc
> +//
You may need to add a license block instead.

2023-10-31 11:50 UTC, TaekyungHeo commented on extern/statistics/GStats.cc
> +  //Report::field("BEGIN GStats::report %s", str);
Please remove commented-out codes.

2023-11-06 22:58 UTC, beckmabd requested changes

2023-11-06 22:58 UTC, beckmabd commented on extern/statistics/GStats.cc
> +  //store->erase(cpos);
please remove commented out code here and the couple lines later.

2023-11-06 22:58 UTC, beckmabd commented on extern/statistics/GStats.hh
> +//
license and copyright block

2023-11-06 22:58 UTC, beckmabd commented on extern/statistics/GStatsIoActivity.cc
> +//
license and copyright

2023-11-06 22:58 UTC, beckmabd commented on extern/statistics/GStatsIoActivity.hh
> +//
license and copyright

2023-11-09 09:39 UTC, willjwon commented
@dkadiyala3 I think this PR will experience merge conflicts with the latest main branch, due to the Network API changes in the analytical backend 2.0. I'll look into this and try creating a patch branch if possible. Thanks!

2024-04-24 18:25 UTC, closed without merging

2024-04-24 18:26 UTC, jinsun-yoo commented
Close this PR for now due to updates in network backend.